version: "3.8"

services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: $PG_USERNAME
      POSTGRES_PASSWORD: $PG_PASSWORD
      POSTGRES_DB: $PG_DATABASE
    ports:
      - $PG_PORT:$PG_PORT
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U $PG_USERNAME -d $PG_DATABASE
      interval: 1s
      timeout: 5s
      retries: 5
  backend:
    depends_on:
      postgres:
        condition: service_healthy
    build: ./backend
    restart: always
    ports:
      - $BACKEND_PORT:$BACKEND_PORT
    environment:
      PG_HOST: postgres
      PG_USERNAME: $PG_USERNAME
      PG_PASSWORD: $PG_PASSWORD
      PG_DATABASE: $PG_DATABASE
      BACKEND_PORT: $BACKEND_PORT
      SECRET: $SECRET
      REFRESH_SECRET: $REFRESH_SECRET
    stdin_open: true
    tty: true
  tile-server:
    build: ./tile-server
    restart: always
    ports:
      - $TILESERVER_PORT:$TILESERVER_PORT
  frontend:
    build: ./frontend
    restart: always
    ports:
      - $FRONTEND_PORT:80

volumes:
  pgdata:
