# @name login
POST http://localhost:3000/users/register
Content-Type: application/json

{
  "username": "a",
  "password": "aaaaaa"
}
###
# @name login
POST http://localhost:3000/users/login
Content-Type: application/json

{
  "username": "a",
  "password": "aaaaaa"
}
###
POST http://localhost:3000/users/login
Content-Type: application/json

{
  "username": "pekka",
  "password": "VÄÄRÄ"
}
### Refresh token test
# @name login
GET http://localhost:3000/users/refresh
Authorization: Bearer {{login.response.body.refreshToken}}
### Refresh token test with wrong token
GET http://localhost:3000/users/refresh
Authorization: Bearer {{login.response.body.token}}
### Refresh token test without token
GET http://localhost:3000/users/refresh
### Change password
PUT http://localhost:3000/users/password
Authorization: Bearer {{login.response.body.token}}
Content-Type: application/json

{
  "password": "aaaaaa"
}
### Delete user
DELETE http://localhost:3000/users/delete
Authorization: Bearer {{login.response.body.token}}

### Paths
GET http://localhost:3000/paths
Authorization: Bearer {{login.response.body.token}}
### new path
POST http://localhost:3000/paths
Authorization: Bearer {{login.response.body.token}}
Content-Type: application/json

{
  "title": "polku2",
  "path": [1]
}
