# @name login
POST http://localhost:3000/users/register
Content-Type: application/json

{
  "username": "matti",
  "password": "salainen"
}
###
# @name login
POST http://localhost:3000/users/login
Content-Type: application/json

{
  "username": "matti",
  "password": "salainen"
}
###
POST http://localhost:3000/users/login
Content-Type: application/json

{
  "username": "pekka",
  "password": "VÄÄRÄ"
}
### Refresh token test
GET http://localhost:3000/users/refresh
Authorization: Bearer {{login.response.body.refreshToken}}
### Refresh token test with wrong token
GET http://localhost:3000/users/refresh
Authorization: Bearer {{login.response.body.token}}
### Refresh token test without token
GET http://localhost:3000/users/refresh
### Paths
GET http://localhost:3000/paths
Authorization: Bearer {{login.response.body.token}}
